# Generated by Django 2.2.3 on 2019-08-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_password',
            new_name='customer_password',
        ),
    ]
