# Generated by Django 2.2.3 on 2019-08-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20190831_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='item',
            new_name='user',
        ),
    ]
