# Generated by Django 2.2.3 on 2019-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20190831_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cart_item',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
