# Generated by Django 2.2.3 on 2019-08-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20190831_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
