# Generated by Django 2.2.3 on 2019-09-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_usercart_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='user',
            new_name='customer',
        ),
    ]
