# Generated by Django 2.2.3 on 2019-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190828_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='items',
            field=models.FileField(upload_to='assets'),
        ),
    ]
